pipeline:
  name: Liberty Deploy Pipeline
  identifier: liberty_deploy_pipeline
  projectIdentifier: appliberty
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Deploy Stage
        identifier: deploy_stage
        description: ""
        type: Deployment
        spec:
          deploymentType: Ssh
          service:
            serviceRef: <+input>
            serviceInputs: <+input>
          infrastructure:
            environmentRef: <+input>
            infrastructureDefinitionRef: <+input>
            infrastructureDetails:
              type: PhysicalServer
              spec:
                hosts: <+input>
          execution:
            steps:
              - step:
                  name: Download and Deploy EAR
                  identifier: download_deploy_ear
                  type: Command
                  timeout: 10m
                  spec:
                    onDelegate: false
                    commandUnits:
                      - identifier: fetch_and_copy
                        name: Fetch EAR from GitHub
                        type: Script
                        spec:
                          shell: Bash
                          source:
                            type: Inline
                            spec:
                              script: |-
                                TARGET_DIR="/opt/ibm/wlp/usr/servers/defaultServer/dropins"
                                FILENAME="liberty-demo-0.0.1-SNAPSHOT.ear"
                                URL="https://github.com/kilgorjn/liberty-demo/releases/download/<+pipeline.variables.version>/$FILENAME"

                                echo "Downloading version <+pipeline.variables.version>..."
                                curl -L -o "$TARGET_DIR/$FILENAME" "$URL"
            rollbackSteps: []
  variables:
    - name: version
      type: String
      description: "The version number (e.g. 0.0.1)"
      required: true
      value: <+input>
