pipeline:
  name: Liberty Deploy Pipeline
  identifier: liberty_deploy_pipeline
  projectIdentifier: appliberty
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Deploy Stage
        identifier: deploy_stage
        description: ""
        type: Deployment
        spec:
          deploymentType: Ssh
          service:
            serviceRef: liberty_ear
          environment:
            environmentRef: liberty_environment
            deployToAll: false
            infrastructureDefinitions:
              - identifier: Liberty_Infrastructure
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: Download and Deploy EAR
                  identifier: download_deploy_ear
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          set -e
                          TARGET_DIR="/opt/ibm/wlp/usr/servers/defaultServer/dropins"
                          FILENAME="liberty-demo-0.0.1-SNAPSHOT.ear"
                          URL="https://github.com/kilgorjn/liberty-demo/releases/download/<+pipeline.variables.version>/$FILENAME"
                          echo "Downloading version <+pipeline.variables.version>..."
                          curl -L -o "$TARGET_DIR/$FILENAME" "$URL"
                          echo "Deployment complete"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
  variables:
    - name: version
      type: String
      description: ""
      required: true
      value: 1.0.1
